### ISSUE TITLE
Persist Users and Channels

### ISSUE THREAD

**Issue by jorams** [Shirakumo/maiden#1]
Currently, the IRC client only deals with users and channels as strings. This is inconvenient. Instead, they should be `user` and `channel` objects that can be worked with.

There is some trickery involved here, because of the way IRC works. When you are not in the same channel as a user, you basically know nothing about them. If you receive a `PRIVMSG` from someone and a second later you receive another `PRIVMSG` from what looks like the same person, those two messages could come from two different people.

Only if you are in the same channel as a user, you receive updates of them parting, quitting, or changing nicknames. Those updates allow you to keep track of them as specific users.

There's more to it. Replies can also come from servers instead of users. See [the grammar in the RFC.](https://tools.ietf.org/html/rfc2812#section-2.3.1) There is no perfect way to distinguish between them, but we can get far: 
- Servers often send not just the nickname of a user, but also their username and hostname (`nick!user@host`). This is invalid for servers, so if they are there we are dealing with a user. 
- Nicknames are also allowed to contain more characters than server names---`[`, `]`, `\`, ```, `_`, `^`, `{`, `|`, `}`---so if such a character exists we are also dealing with a user.
- Similarly, user nicknames are not allowed to contain dots. Server hostnames often will, so if there is a `.` we know we're dealing with a server.

In the ambiguous case, where the message prefix consists of only a nickname or a servername without a dot anywhere, a choice will have to be made whether or not to consider the sender to be a server or a user. If we know of a user with that nickname, that's who we're dealing with. Otherwise all bets are off.

I am under the impression that all IRC servers send full usernames and hostnames in reply prefixes. If that's true---we could do a quick survey to verify---we can default to treating ambiguous names as server names.

The above is based on my knowledge of the RFC. I may have missed or forgotten something, in which case it could all be much easier than I think.

**Comment by Shinmera** [comment]
Currently the heuristic implemented is as follows:

* If it contains a #, it's a channel
* If it contains a ., it's a server
* Otherwise, it's a user.

See `coerce-user-object` in `users.lisp`

**Comment by Shinmera** [comment]
This is done and seems to be working fine so far (unlike connection perseverance)
